export const appConstants = {
SERVER_ADDRESS: 'http://localhost:3000/',

ROUTE_CHANGE: 'ROUTE_CHANGE',

PRICE_INCREASE: 'PRICE_INCREASE',
PRICE_DECREASE: 'PRICE_DECREASE',
PRICE_SUBMIT: 'PRICE_SUBMIT',
PRICE_RESET: 'PRICE_RESET',

USER_DATA_UPDATE: 'USER_DATA_UPDATE',
USER_TYPE_UPDATE: 'USER_TYPE_UPDATE',

SIGN_IN: 'SIGN_IN',
REMEMBER_ME: 'REMEMBER_ME',
REGISTER: 'REGISTER',
SIGN_IN_ERROR: 'SIGN_IN_ERROR',
SIGN_IN_ERROR_RESET: 'SIGN_IN_ERROR_RESET',

SIGN_OUT: 'SIGN_OUT',

ADMIN_USER_LIST: 'ADMIN_USER_LIST'
};