export const appConstants = {
SERVER_ADDRESS: 'http://localhost:3000/',

ROUTE_CHANGE: 'ROUTE_CHANGE',

PRICE_INCREASE: 'PRICE_INCREASE',
PRICE_DECREASE: 'PRICE_DECREASE',
PRICE_SUBMIT: 'PRICE_SUBMIT',
PRICE_SUBMIT_DONE: 'PRICE_SUBMIT_DONE',
PRICE_RESET: 'PRICE_RESET',

USER_DATA_UPDATE: 'USER_DATA_UPDATE',
USER_TYPE_UPDATE: 'USER_TYPE_UPDATE',

SIGN_IN: 'SIGN_IN',
REMEMBER_ME: 'REMEMBER_ME',
REGISTER: 'REGISTER',
SIGN_IN_ERROR: 'SIGN_IN_ERROR',
SIGN_IN_ERROR_RESET: 'SIGN_IN_ERROR_RESET',

SIGN_OUT: 'SIGN_OUT',

LOAD_ADMIN_USER_LIST: 'LOAD_ADMIN_USER_LIST',
UPDATE_ADMIN_USER_LIST: 'UPDATE_ADMIN_USER_LIST',
ADMIN_RESET_CURRENT_VALUES: 'ADMIN_RESET_CURRENT_VALUES',
ADMIN_PROCESSING_START: 'ADMIN_PROCESSING_START',
ADMIN_PROCESSING_DONE: 'ADMIN_PROCESSING_DONE',

LOAD_STATS_DATA: 'LOAD_STATS_DATA',
UPDATE_STATS_DATA: 'UPDATE_STATS_DATA',
UPDATE_STATS_START_DATE: 'UPDATE_STATS_START_DATE',
UPDATE_STATS_END_DATE: 'UPDATE_STATS_END_DATE',
STATS_PROCESSING_START: 'STATS_PROCESSING_START',
STATS_PROCESSING_DONE: 'STATS_PROCESSING_DONE',

SCREEN_RESIZE: 'SCREEN_RESIZE',
CHART_RENDER: 'CHART_RENDER'
};